### ISSUE TITLE
something wrong when running demo

### ISSUE THREAD

**Issue by LCsee** [fwilliams/neural-splines#6]
(neural-splines) root@2a03cc470002:/app/neural-splines# python fit.py demo_data/bunny.ply 10_000 128 recon.ply
Traceback (most recent call last):
  File "fit.py", line 8, in <module>
    from neural_splines import load_point_cloud, fit_model_to_pointcloud, eval_model_on_grid, point_cloud_bounding_box
  File "/app/neural-splines/neural_splines/__init__.py", line 6, in <module>
    import falkon
  File "/root/miniconda3/envs/neural-splines/lib/python3.7/site-packages/falkon/__init__.py", line 3, in <module>
    from . import kernels, optim, preconditioner, center_selection
  File "/root/miniconda3/envs/neural-splines/lib/python3.7/site-packages/falkon/preconditioner/__init__.py", line 1, in <module>
    from .flk_preconditioner import FalkonPreconditioner
  File "/root/miniconda3/envs/neural-splines/lib/python3.7/site-packages/falkon/preconditioner/flk_preconditioner.py", line 8, in <module>
    from falkon.la_helpers import mul_triang, copy_triang, trsm
  File "/root/miniconda3/envs/neural-splines/lib/python3.7/site-packages/falkon/la_helpers/__init__.py", line 1, in <module>
    from .wrapper import *
  File "/root/miniconda3/envs/neural-splines/lib/python3.7/site-packages/falkon/la_helpers/wrapper.py", line 23, in <module>
    from falkon.la_helpers.cuda_la_helpers import (
ModuleNotFoundError: No module named 'falkon.la_helpers.cuda_la_helpers'

**Comment by LCsee** [comment]
Thank you very much!
